In [6]:
import pandas as pd
df = pd.read_csv('경찰청_범죄 발생 시간대 및 요일_20191231.csv', encoding='euc-kr')
df

,범죄대분류,범죄중분류,0시00분-02시59분,03시00분-05시59분,06시00분-08시59분,09시00분-11시59분,12시00분-14시59분,15시00분-17시59분,18시00분-20시59분,21시00분-23시59분,미상,일,월,화,수,목,금,토
0,강력범죄,살인기수,15,21,20,28,38,33,43,49,50,38,45,48,40,37,49,40
1,강력범죄,살인미수등,33,50,29,44,46,60,66,82,72,71,70,68,62,73,85,53
2,강력범죄,강도,105,131,44,59,68,72,81,107,131,111,113,116,105,124,121,108
3,강력범죄,강간,630,885,417,293,325,311,425,719,1305,869,686,734,719,682,722,898
4,강력범죄,유사강간,102,110,57,62,60,55,66,89,181,145,99,109,92,89,112,136
5,강력범죄,강제추행,1855,1921,1293,1163,1300,1706,2189,2901,2792,2580,2272,2306,2358,2231,2542,2831
6,강력범죄,기타 강간 강제추행등,36,47,12,26,20,37,30,40,77,58,53,45,49,39,43,38
7,강력범죄,방화,144,151,105,124,109,173,189,228,139,209,181,181,209,170,206,206
8,절도범죄,절도,13088,14167,13094,21501,27167,28553,27229,20568,21590,25466,26239,25671,26061,26098,28156,29266
9,폭력범죄,상해,4166,3408,2247,2967,3025,3684,4585,7433,5343,5693,4908,5063,5038,5110,5270,5776
10,폭력범죄,폭행,19226,16377,9345,11591,12509,14791,20704,34120,18534,25865,19966,20766,20981,21080,22045,26494
11,폭력범죄,체포 감금,96,106,76,122,147,146,135,185,230,180,189,170,171,169,196,168
12,폭력범죄,협박,1316,1036,1339,2288,2251,2687,3304,3437,3364,2886,3013,3039,3072,2961,3040,3011
13,폭력범죄,약취 유인,10,12,17,29,41,48,32,13,48,27,40,41,34,32,40,36
14,폭력범죄,폭력행위등,1234,1263,460,450,508,704,936,1427,1368,1544,1126,1100,1086,1001,1063,1430
15,폭력범죄,공갈,135,122,74,388,455,590,599,507,1977,483,818,740,757,744,756,549
16,폭력범죄,손괴,5107,4556,4014,5277,4983,6289,9323,10822,7775,8617,7974,7634,7766,7989,8788,9378
17,지능범죄,직무유기,2,3,8,123,33,21,9,5,386,24,108,123,106,99,102,28
18,지능범죄,직권남용,8,11,12,135,48,40,26,15,379,44,126,118,97,107,136,46
19,지능범죄,증수뢰,0,0,2,25,11,6,8,4,204,13,46,42,52,42,45,20
20,지능범죄,통화,9,9,27,183,115,95,41,22,479,35,186,169,187,177,178,48
21,지능범죄,문서 인장,174,134,63,1688,747,464,275,290,7508,620,2130,1971,1840,2032,1978,772
22,지능범죄,유가증권인지,0,1,2,27,9,15,7,2,77,8,22,16,30,21,24,19
23,지능범죄,사기,5443,3949,3056,39184,30405,21648,13930,12387,174470,20814,52740,51876,51225,51654,52039,24124
24,지능범죄,횡령,2754,2526,2780,6781,6586,6584,6646,6367,17484,7231,8559,8128,8318,8460,9317,8495
25,지능범죄,배임,3,4,21,1123,277,68,39,8,3023,248,859,730,787,735,905,302
26,풍속범죄,성풍속범죄,736,597,773,1126,1225,1724,1675,1931,3358,1614,1957,1956,2066,1900,1982,1670
27,풍속범죄,도박범죄,184,112,114,456,488,853,868,819,4114,915,1106,1174,1237,1304,1291,981
28,특별경제범죄,특별경제범죄,1688,1426,1333,6702,5340,4802,3768,4320,22021,3948,8724,8608,8477,8432,8502,4709
29,마약범죄,마약범죄,244,214,151,635,773,890,776,674,3681,789,1278,1352,1219,1195,1272,933
30,보건범죄,보건범죄,596,404,140,880,694,1009,893,1747,6207,934,2051,2096,1962,2043,2085,1399
31,환경범죄,환경범죄,42,53,117,458,290,190,90,126,2511,168,749,696,652,653,696,263
32,교통범죄,교통범죄,24513,23438,37189,44265,45675,53506,58164,70537,20067,47698,51459,53605,54509,54846,58103,57134
33,노동범죄,노동범죄,20,41,80,124,125,117,53,78,337,85,162,139,168,175,143,103
34,안보범죄,안보범죄,2,0,0,10,18,10,3,6,120,36,25,13,22,25,24,24
35,선거범죄,선거범죄,0,1,22,121,53,34,38,3,339,65,90,91,100,113,95,57
36,병역범죄,병역범죄,3,1,20,1440,285,55,58,19,10831,111,3068,3580,1940,2082,1834,97
37,기타범죄,기타범죄,10376,9184,9935,31337,22841,20037,18200,22421,95837,25278,39244,37277,36996,37250,37367,26756

In [5]:
df2 = pd.read_csv('경찰청_범죄 발생 장소별 통계_20241231.csv', encoding='euc-kr')
df2

,범죄대분류,범죄중분류,단독주택_다가구_다중,아파트,다세대_연립,오피스텔_원룸,기타거주시설_기숙사 등,고속도로,자동차 전용도로,일반도로,...,야외_산야,해안,폐가_공터,공중화장실,관공서,군사기지_군사시설,구금장소,사회복지시설,기타,미상
0,강력범죄,살인기수,35,67,44,14,8,0,0,1,...,11,0,0,1,1,0,1,0,32,3
1,강력범죄,살인미수등,50,95,69,22,10,1,0,21,...,15,1,1,0,2,0,1,1,91,2
2,강력범죄,강도,26,21,13,33,3,0,0,20,...,16,0,4,4,2,0,1,0,83,2
3,강력범죄,강간,357,712,581,567,62,1,0,18,...,21,2,8,39,4,1,0,4,356,31
4,강력범죄,유사강간,59,107,106,103,28,0,0,5,...,9,0,2,20,0,0,1,1,56,2
5,강력범죄,강제추행,420,903,496,442,110,18,2,294,...,179,5,11,37,76,38,71,47,2119,60
6,강력범죄,기타 강간/강제추행등,15,32,19,12,4,0,0,1,...,2,0,0,3,0,0,0,0,11,0
7,강력범죄,방화,160,191,124,43,27,1,0,22,...,28,1,7,15,22,0,2,1,161,2
8,절도범죄,절도범죄,5203,14510,5422,2838,827,39,11,5113,...,6363,106,649,400,320,26,20,123,37580,1013
9,폭력범죄,상해,1251,2407,1009,604,180,57,19,1232,...,479,13,53,30,88,12,26,67,3836,65
10,폭력범죄,폭행,5262,17029,6520,2488,726,188,148,8838,...,2485,40,197,118,481,84,188,259,22731,538
11,폭력범죄,체포/감금,54,109,72,76,10,16,4,61,...,13,0,0,3,1,0,6,4,173,5
12,폭력범죄,협박,1787,4439,2035,792,277,407,196,2802,...,310,6,19,6,126,15,60,35,5329,572
13,폭력범죄,약취/유인,16,57,20,9,1,0,0,20,...,10,0,0,0,0,0,1,1,68,2
14,폭력범죄,폭력행위등,194,403,145,132,62,0,0,286,...,188,5,51,16,29,21,8,9,1555,37
15,폭력범죄,공갈,309,707,198,116,94,1,0,73,...,42,1,9,3,42,9,9,4,2891,647
16,폭력범죄,손괴,2548,7074,3032,1456,360,41,36,3785,...,2322,13,170,100,71,2,4,27,11680,306
17,지능범죄,직무유기,10,14,7,6,7,2,0,13,...,7,1,0,0,574,3,16,2,281,67
18,지능범죄,직권남용,20,34,16,2,3,1,0,34,...,11,1,1,0,723,6,44,1,466,115
19,지능범죄,증수뢰,1,3,1,1,3,0,0,2,...,1,0,0,0,51,2,0,1,145,31
20,지능범죄,통화,4,2,1,1,1,0,0,5,...,0,0,0,0,3,0,0,0,125,48
21,지능범죄,문서/인장,199,719,126,96,95,18,2,300,...,30,1,7,0,1334,11,6,27,6233,1596
22,지능범죄,유가증권인지,2,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,29,5
23,지능범죄,사기,12032,24648,7161,4215,4157,1282,376,3975,...,1534,38,141,4,1625,123,113,88,231889,78255
24,지능범죄,횡령,632,2424,761,491,257,62,22,2680,...,1652,40,82,639,178,4,13,45,22950,4082
25,지능범죄,배임,41,187,25,37,39,1,0,1,...,18,0,2,0,105,2,0,3,2572,441
26,풍속범죄,성풍속범죄,826,2934,1026,707,210,5,0,256,...,195,24,3,936,33,69,4,4,5516,1252
27,풍속범죄,도박범죄,663,1039,365,225,149,0,0,7,...,20,0,2,0,2,44,0,3,3449,802
28,특별경제범죄,특별경제범죄,3496,11128,2889,1155,1226,20,2,612,...,360,7,24,5,272,9,2,71,48022,18164
29,마약범죄,마약범죄,1419,906,1069,612,110,16,2,206,...,388,1,25,27,21,10,8,1,3182,334
30,보건범죄,보건범죄,171,265,117,488,82,5,2,117,...,121,4,8,0,16,0,1,6,2541,357
31,환경범죄,환경범죄,18,21,8,1,5,0,0,48,...,487,5,90,0,2,0,0,0,1784,129
32,교통범죄,교통범죄,108,1591,132,78,58,12027,3230,199980,...,301,4,27,0,73,2,2,5,7548,451
33,노동범죄,노동범죄,1,3,0,1,1,0,0,1,...,1,0,0,0,21,0,0,2,190,26
34,안보범죄,안보범죄,16,18,4,24,13,0,0,1,...,3,0,0,0,11,2,0,0,123,27
35,선거범죄,선거범죄,24,59,13,7,14,0,0,59,...,15,0,1,0,202,0,1,9,862,82
36,병역범죄,병역범죄,377,504,309,167,93,1,0,10,...,39,0,0,0,393,1520,2,22,5357,1324
37,기타범죄,기타범죄,11451,25354,10782,5464,2490,965,374,24995,...,4523,76,348,178,9385,714,192,552,87320,16929

NameError: name 'pd' is not defined